import type { ImportedEquipmentFddRule } from "./importedEquipmentCatalog.js";

type ImportedEquipmentRuleId = ImportedEquipmentFddRule["id"];
type ImportedEquipmentType = ImportedEquipmentFddRule["equipmentType"];

/**
 * English display names for every rule imported from the equipment DOCX files.
 *
 * Keep the source wording in importedEquipmentCatalog.ts unchanged for provenance.
 * These labels are the user-facing, deployment-oriented English equivalents.
 */
export const IMPORTED_EQUIPMENT_RULE_DISPLAY_NAMES = {
  "VAV-01": "High Zone Temperature",
  "VAV-02": "Low Zone Temperature",
  "VAV-03": "Insufficient Cooling Capacity",
  "VAV-04": "Airflow Below Setpoint",
  "VAV-05": "Airflow Above Setpoint",
  "VAV-06": "Damper Command and Feedback Mismatch",
  "VAV-07": "Damper Fails to Open on Command",
  "VAV-08": "Damper Fails to Close on Command",
  "VAV-09": "Significant Airflow with Damper Closed",
  "VAV-10": "Invalid Airflow Setpoint",
  "VAV-11": "Reheat Valve Fails to Open on Command",
  "VAV-12": "Reheat Valve Fails to Close on Command",
  "VAV-13": "Significant Heating with Reheat Valve Closed",
  "VAV-14": "Insufficient Reheat Capacity",
  "VAV-15": "Airflow Sensor Fault",
  "VAV-16": "Zone Temperature Sensor Fault",
  "VAV-17": "VAV Discharge Air Temperature Sensor Fault",

  "PMP-01": "Pump Fails to Run on Command",
  "PMP-02": "Pump Runs without Command",
  "PMP-03": "No Flow while Pump Is Running",
  "PMP-04": "Insufficient Pump Differential Pressure",
  "PMP-05": "Excessive Pump Differential Pressure",
  "PMP-06": "Pump Differential Pressure Control Oscillation",
  "PMP-07": "Pump Variable-Frequency Drive Fault",
  "PMP-08": "Low Pump Inlet Pressure",
  "PMP-09": "High Pump Inlet Pressure",
  "PMP-10": "Low Pump Outlet Pressure",
  "PMP-11": "High Pump Outlet Pressure",
  "PMP-12": "Reversed Pump Inlet-to-Outlet Pressure Relationship",
  "PMP-13": "Check Valve Leakage",
  "PMP-14": "Isolation Valve Fails to Open",
  "PMP-15": "Chilled-Water Pump Inlet Pressure Sensor Fault",
  "PMP-16": "Chilled-Water Pump Outlet Pressure Sensor Fault",
  "PMP-17": "Pump Speed Sensor Fault",
  "PMP-18": "Differential Pressure Sensor Fault",

  "FCU-01": "FCU Fails to Run on Command",
  "FCU-02": "FCU Runs without Command",
  "FCU-03": "Fan Speed Command and Feedback Mismatch",
  "FCU-04": "High Room Temperature",
  "FCU-05": "Low Room Temperature",
  "FCU-06": "Unmet Cooling Demand at Maximum FCU Output",
  "FCU-07": "Unmet Heating Demand at Maximum FCU Output",
  "FCU-08": "Insufficient Discharge-Air Cooling at High Cooling-Valve Position",
  "FCU-09": "Significant Cooling with Cooling Valve Closed",
  "FCU-10": "Insufficient Discharge-Air Heating at High Heating-Valve Position",
  "FCU-11": "Significant Heating with Heating Valve Closed",
  "FCU-12": "Simultaneous Cooling and Heating Valve Operation",
  "FCU-13": "Cooling Valve Fails to Open on Command",
  "FCU-14": "Cooling Valve Fails to Close on Command",
  "FCU-15": "Heating Valve Fails to Open on Command",
  "FCU-16": "Heating Valve Fails to Close on Command",
  "FCU-17": "Filter Blockage",
  "FCU-18": "Discharge Air Temperature Sensor Fault",
  "FCU-19": "Return Air Temperature Sensor Fault",
  "FCU-20": "Room Temperature Sensor Fault",

  "CT-01": "Cooling Tower Fails to Run on Command",
  "CT-02": "Cooling Tower Runs without Command",
  "CT-03": "Cooling Tower Fan Speed Abnormally Low",
  "CT-04": "Cooling Tower Fan Speed Abnormally High",
  "CT-05": "Cooling Tower Bypass Valve Unexpectedly Open",
  "CT-06": "Cooling Tower Bypass Valve Stuck Closed",
  "CT-07": "Low Cooling Tower Basin Water Level",
  "CT-08": "High Cooling Tower Basin Water Level",
  "CT-09": "Cooling Tower Make-Up Water Valve Fault",
  "CT-10": "Outdoor Air Dry-Bulb Temperature Sensor Fault",
  "CT-11": "Outdoor Air Wet-Bulb Temperature Sensor Fault",
  "CT-12": "Cooling Tower Fan Speed Sensor Fault",

  "AHU-01": "AHU Start Failure",
  "AHU-02": "Unexpected AHU Shutdown during Operation",
  "AHU-03": "AHU Runs without Command",
  "AHU-04": "Supply Fan Fails to Run on Command",
  "AHU-05": "Supply Fan Runs without Command",
  "AHU-06": "Supply Fan Speed Abnormally High",
  "AHU-07": "Supply Fan Speed Abnormally Low",
  "AHU-08": "Supply Fan Power Abnormally High",
  "AHU-09": "Supply Fan Power Abnormally Low",
  "AHU-10": "Insufficient Supply Duct Static Pressure",
  "AHU-11": "Excessive Supply Duct Static Pressure",
  "AHU-12": "High Supply Air Temperature",
  "AHU-13": "Low Supply Air Temperature",
  "AHU-14": "High Chilled-Water Supply Temperature",
  "AHU-15": "Low Hot-Water Supply Temperature",
  "AHU-16": "Insufficient Cooling Performance",
  "AHU-17": "Significant Cooling with Cooling Valve Closed",
  "AHU-18": "Insufficient Heating Performance",
  "AHU-19": "Significant Heating with Heating Valve Closed",
  "AHU-20": "Simultaneous Cooling and Heating Valve Operation",
  "AHU-21": "Cooling Valve Stuck Closed",
  "AHU-22": "Cooling Valve Stuck Open",
  "AHU-23": "Heating Valve Stuck Closed",
  "AHU-24": "Heating Valve Stuck Open",
  "AHU-25": "Invalid Mixed-Air Temperature Relationship",
  "AHU-26": "Outdoor Air Damper Stuck Closed",
  "AHU-27": "Outdoor Air Damper Stuck Open",
  "AHU-28": "Return Air Damper Stuck Closed",
  "AHU-29": "Return Air Damper Stuck Open",
  "AHU-30": "Exhaust Air Damper Stuck Closed",
  "AHU-31": "Exhaust Air Damper Stuck Open",
  "AHU-32": "Insufficient Outdoor Airflow",
  "AHU-33": "Filter Blockage",
  "AHU-34": "Damaged or Missing Filter",
  "AHU-35": "Supply Duct Static Pressure Sensor Fault",
  "AHU-36": "Filter Differential Pressure Sensor Fault",
  "AHU-37": "Supply Air Temperature Sensor Fault",
  "AHU-38": "Mixed Air Temperature Sensor Fault",
  "AHU-39": "Return Air Temperature Sensor Fault",
  "AHU-40": "Outdoor Air Temperature Sensor Fault",
  "AHU-41": "Supply Air Humidity Sensor Fault",
  "AHU-42": "Mixed Air Humidity Sensor Fault",
  "AHU-43": "Return Air Humidity Sensor Fault",
  "AHU-44": "Outdoor Air Humidity Sensor Fault"
} as const satisfies Record<ImportedEquipmentRuleId, string>;

export const IMPORTED_EQUIPMENT_CATEGORY_DISPLAY_LABELS = {
  "区域温度控制": "Zone Temperature Control",
  "风量控制": "Airflow Control",
  "风阀": "Damper",
  "风量设定值": "Airflow Setpoint",
  "再热": "Reheat",
  "传感器": "Sensor",
  "运行状态": "Operation",
  "水力性能": "Hydraulic Performance",
  "控制": "Control",
  "压力异常": "Pressure",
  "阀门": "Valve",
  "风机": "Fan",
  "温度控制": "Temperature Control",
  "冷却/加热阀": "Cooling / Heating Valve",
  "过滤器": "Filter",
  "旁通与水位": "Bypass and Water Level",
  "静压控制": "Static Pressure Control",
  "送风温度控制": "Supply Air Temperature Control",
  "盘管/水侧": "Coil / Water Side",
  "执行器": "Actuator",
  "混风/新风": "Mixed / Outdoor Air",
  "过滤器/风管": "Filter / Duct"
} as const;

/** English descriptions for the source symbols that are currently presented by the UI. */
export const IMPORTED_EQUIPMENT_SOURCE_DESCRIPTION_ENGLISH = {
  "vav:VAV_{cmd}": "VAV box enable command",
  "vav:DAM_{cmd}": "Damper position command",
  "vav:DAM_{pos}": "Actual damper position",
  "vav:AFLOW": "Actual supply airflow",
  "vav:AFLOW_{sp}": "Supply airflow setpoint",
  "vav:AFLOW_{min}": "Minimum airflow setpoint",
  "vav:AFLOW_{max}": "Maximum airflow setpoint",
  "vav:T_{zone}": "Zone air temperature",
  "vav:T_{zone_sp}": "Zone air temperature setpoint",
  "vav:T_{da}": "VAV discharge air temperature",
  "vav:T_{sa}": "AHU supply air temperature",
  "vav:SP": "Duct static pressure",
  "vav:RHV": "Reheat valve position",
  "vav:HWST": "Hot-water supply temperature",
  "vav:OCC": "Occupancy status",
  "vav:CO_{2}": "Zone carbon-dioxide concentration",

  "pump:PUMP_{cmd}": "Pump enable command",
  "pump:PUMP_{sts}": "Pump operating status",
  "pump:PUMP_{speed}": "Pump frequency or rotational speed",
  "pump:PUMP_{power}": "Pump electrical power",
  "pump:PUMP_{current}": "Pump electrical current",
  "pump:FLOW": "Water flow rate, including chilled-water or condenser-water flow",
  "pump:DP": "Pump differential pressure, including chilled-water or condenser-water service",
  "pump:DP_{sp}": "Pump differential pressure setpoint, including chilled-water or condenser-water service",
  "pump:P_{in}": "Pump inlet pressure",
  "pump:P_{out}": "Pump outlet pressure",
  "pump:VALVE_{pos}": "Associated valve position",
  "pump:VFD_{alm}": "Variable-frequency drive alarm",
  "pump:PUMP_{alm}": "Pump alarm",

  "fcu:FCU_{cmd}": "FCU enable command",
  "fcu:FCU_{sts}": "FCU operating status",
  "fcu:FAN_{cmd}": "Fan enable command",
  "fcu:FAN_{sts}": "Fan operating status",
  "fcu:FAN_{speed}": "Fan speed stage or rotational speed",
  "fcu:FAN_{power}": "Fan electrical power",
  "fcu:T_{zone}": "Room air temperature",
  "fcu:T_{zone,sp}": "Room air temperature setpoint",
  "fcu:T_{sa}": "FCU discharge air temperature",
  "fcu:T_{ra}": "FCU return air or room return air temperature",
  "fcu:CWV": "Cooling-water valve position",
  "fcu:HWV": "Hot-water valve position",
  "fcu:CHWST": "Chilled-water supply temperature",
  "fcu:HWST": "Hot-water supply temperature",
  "fcu:OCC": "Occupancy status",
  "fcu:COND_{h}": "Condensate pan water level",
  "fcu:FILTER_{dp}": "Filter differential pressure",

  "cooling_tower:CT_{cmd}": "Cooling tower enable command",
  "cooling_tower:CT_{sts}": "Cooling tower operating status",
  "cooling_tower:CT_{fan_cmd}": "Cooling tower fan enable command",
  "cooling_tower:CT_{fan_sts}": "Cooling tower fan operating status",
  "cooling_tower:CT_{fan_speed}": "Cooling tower fan frequency or rotational speed",
  "cooling_tower:CT_{fan_power}": "Cooling tower fan electrical power",
  "cooling_tower:CT_{tin}": "Condenser-water temperature entering the cooling tower",
  "cooling_tower:CT_{tout}": "Condenser-water temperature leaving the cooling tower",
  "cooling_tower:CW_{flow}": "Condenser-water flow rate",
  "cooling_tower:T_{oat}": "Outdoor air dry-bulb temperature",
  "cooling_tower:T_{oawb}": "Outdoor air wet-bulb temperature",
  "cooling_tower:CT_{basin_t}": "Cooling tower basin water temperature",
  "cooling_tower:CT_{basin_h}": "Cooling tower basin water level",
  "cooling_tower:CT_{valve}": "Cooling tower bypass valve position",
  "cooling_tower:CT_APPROACH": "Cooling tower approach temperature, leaving condenser-water temperature minus outdoor wet-bulb temperature",
  "cooling_tower:CT_{∆t}": "Cooling tower temperature drop, entering minus leaving condenser-water temperature",

  "ahu:AHU_{cmd}": "AHU enable command",
  "ahu:AHU_{sts}": "AHU operating status",
  "ahu:FAN_{cmd}": "Supply fan enable command",
  "ahu:FAN_{sts}": "Supply fan operating status",
  "ahu:FAN_{speed}": "Supply fan frequency",
  "ahu:FAN_{power}": "Supply fan electrical power",
  "ahu:T_{sa}": "Supply air temperature",
  "ahu:T_{sa_sp}": "Supply air temperature setpoint",
  "ahu:T_{ma}": "Mixed air temperature",
  "ahu:T_{ra}": "Return air temperature",
  "ahu:T_{oa}": "Outdoor air temperature",
  "ahu:∅_{sa}": "Supply air relative humidity",
  "ahu:∅_{ra}": "Return air relative humidity",
  "ahu:∅_{oa}": "Outdoor air relative humidity",
  "ahu:SP": "Duct static pressure",
  "ahu:SP_{sp}": "Duct static pressure setpoint",
  "ahu:CCV": "Cooling coil valve position",
  "ahu:HCV": "Heating coil valve position",
  "ahu:OAD": "Outdoor air damper position",
  "ahu:RAD": "Return air damper position",
  "ahu:EAD": "Exhaust air damper position",
  "ahu:FILTER_{dp}": "Filter differential pressure",
  "ahu:CHWST": "Chilled-water supply temperature",
  "ahu:CHWRT": "Chilled-water return temperature",
  "ahu:HWST": "Hot-water supply temperature",
  "ahu:HWRT": "Hot-water return temperature",
  "ahu:CO_{2}": "Return-air or zone carbon-dioxide concentration"
} as const;

export function importedEquipmentRuleDisplayName(ruleId: ImportedEquipmentRuleId): string {
  return IMPORTED_EQUIPMENT_RULE_DISPLAY_NAMES[ruleId];
}

export function importedEquipmentCategoryDisplayLabel(rule: Pick<ImportedEquipmentFddRule, "id" | "category">): string {
  if (!rule.category) return rule.id === "PMP-17" ? "Sensor" : "Uncategorized";
  return IMPORTED_EQUIPMENT_CATEGORY_DISPLAY_LABELS[rule.category];
}

export function importedEquipmentSourceDescription(
  equipmentType: ImportedEquipmentType,
  sourceSymbol: string
): string | undefined {
  const key = `${equipmentType}:${sourceSymbol}` as keyof typeof IMPORTED_EQUIPMENT_SOURCE_DESCRIPTION_ENGLISH;
  return IMPORTED_EQUIPMENT_SOURCE_DESCRIPTION_ENGLISH[key];
}
