import type {
  EvidenceDefinitionReference,
  EvidenceExecutionRecord,
  EvidenceProducerKind,
  EvidenceReference,
  FaultEvent,
  MetricResult,
  PlannedChartRequest,
  PlannedDashboardRequest,
  PlannedFaultRequest,
  PlannedMetricRequest,
  ReportArtifact,
  ReportPlan,
  ReportScope,
  ResolvedReportPeriod
} from "./contracts.js";
import type {
  ChartEvidenceDefinition,
  FaultEvidenceDefinition,
  MetricEvidenceDefinition
} from "./evidenceDefinitions.js";

export interface EvidenceProducerDescriptor {
  producerKind: EvidenceProducerKind;
  producerId: string;
  producerVersion: string;
}

interface EvidenceToolOutcomeBase {
  sourceRevision?: string;
  evidence?: EvidenceReference[];
}

export type EvidenceToolOutcome<T> =
  | (EvidenceToolOutcomeBase & { status: "complete"; value: T })
  | (EvidenceToolOutcomeBase & { status: "no_data"; reasonCode: string; message: string })
  | (EvidenceToolOutcomeBase & {
      status: "error";
      errorCode: string;
      message: string;
      retryable: boolean;
    });

export interface EvidenceToolContext {
  packageId: string;
  planId: string;
  planRevision: string;
  projectId: string;
  assetRevision: string;
  period: ResolvedReportPeriod;
  equipment: ReportPlan["equipment"];
  requestTimeoutMs: number;
}

export interface MetricToolFact {
  projectId: string;
  metricKey: string;
  scope: ReportScope;
  period: ResolvedReportPeriod;
  definition: EvidenceDefinitionReference;
  observedUnit: string;
  value: number;
  sampleCount: number;
  coverage: number;
  evidence: EvidenceReference[];
}

export interface MetricEvidenceToolInput {
  signal: AbortSignal;
  context: EvidenceToolContext;
  request: PlannedMetricRequest;
  definition: MetricEvidenceDefinition;
}

export interface MetricEvidenceTool {
  descriptor: EvidenceProducerDescriptor;
  execute(input: MetricEvidenceToolInput): Promise<EvidenceToolOutcome<MetricToolFact>>;
}

export interface ReportArtifactCandidate {
  relativePath: string;
  mediaType: ReportArtifact["mediaType"];
  bytes: Uint8Array;
}

export interface ChartToolFact {
  projectId: string;
  chartKey: string;
  scope: ReportScope;
  period: ResolvedReportPeriod;
  definition: EvidenceDefinitionReference;
  title: string;
  artifact: ReportArtifactCandidate;
  evidence: EvidenceReference[];
}

export interface ChartEvidenceToolInput {
  signal: AbortSignal;
  context: EvidenceToolContext;
  request: PlannedChartRequest;
  definition: ChartEvidenceDefinition;
  metricResults: MetricResult[];
  faultEvents: FaultEvent[];
  inputExecutions: EvidenceExecutionRecord[];
}

export interface ChartEvidenceTool {
  descriptor: EvidenceProducerDescriptor;
  execute(input: ChartEvidenceToolInput): Promise<EvidenceToolOutcome<ChartToolFact>>;
}

export interface DashboardToolFact {
  projectId: string;
  dashboardId: string;
  dashboardRevision: string;
  period: ResolvedReportPeriod;
  definition: EvidenceDefinitionReference;
  title: string;
  artifact: ReportArtifactCandidate;
  evidence: EvidenceReference[];
}

export interface DashboardEvidenceToolInput {
  signal: AbortSignal;
  context: EvidenceToolContext;
  request: PlannedDashboardRequest;
}

export interface DashboardEvidenceTool {
  descriptor: EvidenceProducerDescriptor;
  execute(input: DashboardEvidenceToolInput): Promise<EvidenceToolOutcome<DashboardToolFact>>;
}

interface FaultDetectionFactBase {
  faultCode: string;
  startedAt: string;
  evidence: EvidenceReference[];
}

export type FaultDetectionFact =
  | (FaultDetectionFactBase & { status: "active"; observedThrough: string })
  | (FaultDetectionFactBase & { status: "resolved"; endedAt: string });

export interface FaultToolFact {
  projectId: string;
  equipmentId: string;
  equipmentType: string;
  period: ResolvedReportPeriod;
  definition: EvidenceDefinitionReference;
  events: FaultDetectionFact[];
}

export interface FaultEvidenceToolInput {
  signal: AbortSignal;
  context: EvidenceToolContext;
  request: PlannedFaultRequest;
  definition: FaultEvidenceDefinition;
}

export interface FaultEvidenceTool {
  descriptor: EvidenceProducerDescriptor;
  execute(input: FaultEvidenceToolInput): Promise<EvidenceToolOutcome<FaultToolFact>>;
}

export interface ReportArtifactWriteInput extends ReportArtifact {
  /** Safe path segment generated by the executor; sinks must not join raw IDs into filesystem paths. */
  storageNamespace: string;
  /** Audit metadata only. Do not use these opaque IDs as path segments. */
  packageId: string;
  planId: string;
  projectId: string;
  signal: AbortSignal;
  bytes: Uint8Array;
}

export interface ReportArtifactSink {
  write(input: ReportArtifactWriteInput): Promise<void>;
}

export interface ReportEvidenceTools {
  metrics: Partial<Record<MetricEvidenceDefinition["producerKind"], MetricEvidenceTool>>;
  chart: ChartEvidenceTool;
  dashboard: DashboardEvidenceTool;
  fault: FaultEvidenceTool;
  artifactSink: ReportArtifactSink;
}
