/** Single source of truth for enterprise chart styling and execute_code data/chart helpers. */

export const SCIENTIFIC_CHART_CONSTANTS = {
  figsize: [11, 6.5] as const,
  dpi: 300,
  palette: "deep",
  themeStyle: "whitegrid",
  themeContext: "talk",
  figureFacecolor: "#F8FAFC",
  axesFacecolor: "#FFFFFF",
  gridColor: "#E2E8F0",
  textColor: "#0F172A",
  mutedTextColor: "#64748B",
  spineColor: "#CBD5E1"
} as const;

/** Corporate presentation palette — saturated enough for slides, still distinguishable. */
export const COLOR_CYCLE = [
  "#2563EB",
  "#0D9488",
  "#7C3AED",
  "#D97706",
  "#E11D48",
  "#475569",
  "#0891B2",
  "#65A30D"
] as const;

/** Paired with COLOR_CYCLE so fleet lines remain distinguishable in grayscale. */
export const LINE_STYLE_CYCLE = [
  "-",
  "--",
  "-.",
  ":"
] as const;

const DATA_BRIDGE_MINIMAL_EXAMPLE = [
  "combined = build_combined_frame()",
  "fig, axes = plot_timeseries_default(combined, title='Plant overview', ylabel='Value')",
  "path = save_chart(fig, 'overview.png')"
].join("; ");

export function dataBridgeSkillHint(): string {
  return [
    "TOOL DATA BRIDGE (mandatory for execute_code after data tools):",
    "1) load_all_series() returns {label: DataFrame} — iterate `for label, df in load_all_series().items()`; NEVER `for entry in load_all_series()` (entry is a string key, not a manifest dict).",
    "2) Prefer build_combined_frame() for a wide HKT-indexed table; use manifest label or col_series(combined, label) — never guess column names like combined['short_name'].",
    "3) Helpers: load_series_by_label, items_to_frame, downsample_timeseries (first/min/max/last, <=1000 points), normalize_status, resample_status_15m, series_short_label, plot_timeseries_default.",
    "   build_combined_frame() keeps stable full manifest labels and naturally sorts the resulting columns; short suffixes are lookup aliases only — never delete or rename a column just because several points share a metric suffix.",
    "4) Do NOT open outputs/.tool_cache/*_manifest.json by hand.",
    "5) pandas 3: .ffill()/.bfill(); never fillna(method=...); pd.concat(..., sort=False).",
    "6) One execute_code pass ending in save_chart — no debug-only scripts (print columns/shape only).",
    "7) Before plotting: data_coverage(combined) — never drop a selected column; plot_timeseries_default() keeps an explicit No valid samples panel. Wide table rows are sparse (outer join).",
    "8) With request-local history, stdout/stderr are always hidden; non-image artifacts are hidden. Do not print data or summaries; return results through saved charts only.",
    `Minimal pattern: ${DATA_BRIDGE_MINIMAL_EXAMPLE}`
  ].join(" ");
}

export function scientificChartSkillHint(): string {
  const [w, h] = SCIENTIFIC_CHART_CONSTANTS.figsize;
  return [
    "ENTERPRISE CHARTS (mandatory for any figure — fixed presentation style for corporate reports):",
    `Use plot_timeseries_default() for compatible-unit analog history; lower-level helpers are new_figure(), set_chart_title(), plot_series(), chart_color(), format_hkt_axis(), finalize_legend(), and save_chart() — dpi=${SCIENTIFIC_CHART_CONSTANTS.dpi}, base figsize=(${w}, ${h}).`,
    "Style is auto-applied (whitegrid, eight-color fleet palette, distinct line styles, left-aligned title, clean spines) — do NOT customize colors/fonts manually.",
    "DEFAULT timeseries: plot_timeseries_default() keeps 1–4 short series as a line chart on one axis, but renders 5–8 histories spanning at least seven days as small multiples with hourly median and a P10–P90 band. Use layout='overlay' only when the user explicitly requests one-axis comparison.",
    "Small multiples keep empty hourly bins as gaps and switch to independent y-scales when one abnormal range would flatten the other panels; the subtitle discloses aggregation, HKT, and scale mode.",
    "Never mix incompatible units in one plot_timeseries_default() call; use separate figures.",
    "Use plot_status_step(ax, combined, col) only for discrete status (Run_Status/S); never fill_between on power/temperature/flow.",
    "NEVER hard-code COLOR_CYCLE[8] — use chart_color(i) or COLOR_CYCLE[i % len(COLOR_CYCLE)].",
    "mdates is pre-imported — use format_hkt_axis(ax); never mdates.DateFormatter(..., tz=...).",
    "Do NOT sns.set_style/set_theme with custom palettes; do NOT plt.savefig directly.",
    "English-only on-chart text; provide a clear business title through plot_timeseries_default(title=...) or set_chart_title(); every chart script must call save_chart()."
  ].join(" ");
}

/** Detect chart intent without save_chart output — for execute_code sanity check. */
export function chartSanityViolation(userCode: string, newPngCount: number): string | null {
  const trimmed = userCode.trim();
  if (!trimmed) {
    return null;
  }
  const chartIntent =
    /\bnew_figure\s*\(|\bplot_series\s*\(|\bplot_timeseries_default\s*\(|\bplot_series_small_multiples\s*\(|\bplt\.subplots\s*\(|\bplt\.plot\s*\(|\b\.plot\s*\(|\baxes\[\d+\]\.plot\s*\(/i.test(trimmed);
  if (/\bsave_chart\s*\(/i.test(trimmed) || newPngCount > 0) {
    return null;
  }
  const debugOnly =
    /\bprint\s*\(/i.test(trimmed)
    && /\b(build_combined_frame|load_all_series|\.columns|\.shape|data_coverage)\b/i.test(trimmed);
  if (debugOnly && !chartIntent) {
    return "Debug-only execute_code (print columns/shape/coverage) is not allowed after data tools. One pass ending in save_chart().";
  }
  if (chartIntent) {
    return "Chart code detected but save_chart() was not called and no PNG was generated. End chart scripts with save_chart(fig, 'name.png').";
  }
  return null;
}

export function executeCodeInjectedHeader(): string {
  const [figW, figH] = SCIENTIFIC_CHART_CONSTANTS.figsize;
  const dpi = SCIENTIFIC_CHART_CONSTANTS.dpi;
  const colors = COLOR_CYCLE.map((c) => `"${c}"`).join(", ");
  const lineStyles = LINE_STYLE_CYCLE.map((style) => `"${style}"`).join(", ");

  return [
    "# Auto-injected by BuildingAgent execute_code",
    "import json, os, re",
    "from zoneinfo import ZoneInfo",
    "import pandas as pd",
    "import numpy as np",
    "import matplotlib",
    "matplotlib.use('Agg')",
    "import matplotlib.pyplot as plt",
    "import matplotlib.dates as mdates",
    "import seaborn as sns",
    'HKT = ZoneInfo("Asia/Hong_Kong")',
    "",
    "def _natural_sort_key(value):",
    "    # Tagged components avoid comparing ints with strings for mixed labels.",
    "    return tuple((0, int(part)) if part.isdigit() else (1, part.casefold()) for part in re.split(r'(\\d+)', str(value)))",
    "",
    "def load_tool_manifest():",
    "    # entries: [{label, data_file, tool, toolCallId}] — use entry['label'], not entry['name']",
    "    path = os.environ.get('TOOL_CACHE_MANIFEST', '')",
    "    if path and os.path.isfile(path):",
    "        with open(path, encoding='utf-8') as f:",
    "            return json.load(f)",
    "    return {'requestId': os.environ.get('REQUEST_ID', ''), 'entries': []}",
    "",
    "def load_cached_items(data_file, data_key=None):",
    "    with open(data_file, encoding='utf-8') as f:",
    "        payload = json.load(f)",
    "    if isinstance(payload, dict) and isinstance(payload.get('series'), list):",
    "        candidates = payload['series']",
    "        if data_key:",
    "            payload = next((row for row in candidates if isinstance(row, dict) and (row.get('data_key') == data_key or row.get('instanceId') == data_key or row.get('instance_id') == data_key)), {})",
    "        elif len(candidates) == 1:",
    "            payload = candidates[0]",
    "    if isinstance(payload, dict):",
    "        return payload.get('items', payload.get('history', payload))",
    "    return payload",
    "",
    "def items_to_frame(items, value_col='value_num'):",
    "    df = pd.DataFrame(items)",
    "    if df.empty:",
    "        return df",
    "    aliases = {'valueNum': 'value_num', 'valueText': 'value_text', 'instanceId': 'instance_id'}",
    "    rename = {source: target for source, target in aliases.items() if source in df.columns and target not in df.columns}",
    "    if rename:",
    "        df = df.rename(columns=rename)",
    "    if 'ts' in df.columns:",
    "        df['ts'] = pd.to_datetime(df['ts'], utc=True, format='mixed', errors='coerce').dt.tz_convert(HKT)",
    "        df = df.dropna(subset=['ts'])",
    "        df = df.set_index('ts').sort_index(kind='mergesort')",
    "        # Overlapping historical imports can contain the same timestamp more than once.",
    "        # Keep the final source row deterministically so wide-frame joins stay one-to-one.",
    "        df = df[~df.index.duplicated(keep='last')]",
    "    if value_col in df.columns:",
    "        df[value_col] = pd.to_numeric(df[value_col], errors='coerce')",
    "    return df",
    "",
    "def load_series_by_label(label):",
    "    manifest = load_tool_manifest()",
    "    for entry in manifest.get('entries', []):",
    "        if entry.get('label') == label:",
    "            return items_to_frame(load_cached_items(entry['data_file'], entry.get('data_key')))",
    "    raise KeyError(f'No manifest entry for label={label!r}')",
    "",
    "def load_all_series():",
    "    # Returns dict[str, DataFrame] keyed by manifest label — NOT a list of entries.",
    "    out = {}",
    "    for entry in load_tool_manifest().get('entries', []):",
    "        label = entry.get('label') or entry.get('data_key')",
    "        if not label:",
    "            continue",
    "        unique_label = label",
    "        if unique_label in out:",
    "            unique_label = f\"{label}:{entry.get('data_key') or entry.get('toolCallId', len(out))}\"",
    "        out[unique_label] = items_to_frame(load_cached_items(entry['data_file'], entry.get('data_key')))",
    "    return dict(sorted(out.items(), key=lambda item: _natural_sort_key(item[0])))",
    "",
    "def downsample_timeseries(data, value_col='value_num', max_points=1000):",
    "    # M4: preserve first/min/max/last valid values in chronological time buckets.",
    "    if data is None or max_points <= 0:",
    "        return data",
    "    is_series = isinstance(data, pd.Series)",
    "    if is_series:",
    "        frame = data.to_frame(name=data.name or value_col)",
    "        numeric_col = frame.columns[0]",
    "    elif isinstance(data, pd.DataFrame) and value_col in data.columns:",
    "        frame = data",
    "        numeric_col = value_col",
    "    else:",
    "        return data",
    "    numeric = pd.to_numeric(frame[numeric_col], errors='coerce')",
    "    valid_positions = np.flatnonzero(numeric.notna().to_numpy())",
    "    if len(frame) <= max_points:",
    "        return data",
    "    if len(valid_positions) <= max_points:",
    "        sampled = frame.iloc[valid_positions].sort_index()",
    "        return sampled.iloc[:, 0].rename(data.name) if is_series else sampled",
    "    if max_points < 4:",
    "        selected = valid_positions[np.linspace(0, len(valid_positions) - 1, max_points, dtype=int)]",
    "    else:",
    "        bucket_count = max(1, max_points // 4)",
    "        if isinstance(frame.index, pd.DatetimeIndex):",
    "            valid_index = frame.index[valid_positions]",
    "            relative_ns = (valid_index - valid_index[0]).asi8",
    "            span_ns = int(relative_ns[-1])",
    "            width_ns = max(1, (span_ns + bucket_count - 1) // bucket_count)",
    "            # Python integer division avoids nanosecond overflow/float rounding,",
    "            # and clamping guarantees the final timestamp remains in-range.",
    "            bucket_ids = np.array([min(bucket_count - 1, int(delta) // width_ns) for delta in relative_ns], dtype=int)",
    "        else:",
    "            bucket_ids = np.minimum(bucket_count - 1, np.arange(len(valid_positions)) * bucket_count // len(valid_positions))",
    "        selected_positions = []",
    "        for bucket in range(bucket_count):",
    "            bucket_positions = valid_positions[bucket_ids == bucket]",
    "            if len(bucket_positions) == 0:",
    "                continue",
    "            bucket_values = numeric.iloc[bucket_positions].to_numpy(dtype=float)",
    "            selected_positions.extend([",
    "                int(bucket_positions[0]),",
    "                int(bucket_positions[int(np.nanargmin(bucket_values))]),",
    "                int(bucket_positions[int(np.nanargmax(bucket_values))]),",
    "                int(bucket_positions[-1])",
    "            ])",
    "        selected = np.array(sorted(set(selected_positions)), dtype=int)",
    "        # Monotonic buckets can collapse first/min/max/last to two positions.",
    "        # Fill unused capacity uniformly without removing any M4/extreme anchor.",
    "        if len(selected) < max_points:",
    "            remaining_positions = np.setdiff1d(valid_positions, selected, assume_unique=True)",
    "            fill_count = min(max_points - len(selected), len(remaining_positions))",
    "            if fill_count > 0:",
    "                fill_offsets = np.linspace(0, len(remaining_positions) - 1, fill_count, dtype=int)",
    "                selected = np.array(sorted(set(selected.tolist() + remaining_positions[fill_offsets].tolist())), dtype=int)",
    "    sampled = frame.iloc[selected].sort_index()",
    "    return sampled.iloc[:, 0].rename(data.name) if is_series else sampled",
    "",
    "def _robust_gap_threshold_ns(index, gap_factor=3.0, mad_factor=6.0):",
    "    # Polling histories often jitter between roughly one and two nominal intervals.",
    "    # A fixed 1.5x median threshold therefore creates thousands of false gaps.",
    "    if not isinstance(index, pd.DatetimeIndex) or len(index) < 2:",
    "        return None",
    "    time_values_ns = np.array([timestamp.value for timestamp in index], dtype=np.int64)",
    "    positive = np.diff(time_values_ns)",
    "    positive = positive[positive > 0]",
    "    if len(positive) == 0:",
    "        return None",
    "    cadence_ns = float(np.median(positive))",
    "    mad_ns = float(np.median(np.abs(positive - cadence_ns)))",
    "    robust_limit_ns = cadence_ns + mad_factor * 1.4826 * mad_ns",
    "    return max(cadence_ns * gap_factor, robust_limit_ns)",
    "",
    "def _series_with_gap_breaks(series, max_points=1000, gap_factor=3.0):",
    "    # Split before M4 sampling so genuine gaps stay disconnected and extrema survive.",
    "    numeric = pd.to_numeric(series, errors='coerce')",
    "    valid_positions = np.flatnonzero(numeric.notna().to_numpy())",
    "    if len(valid_positions) == 0:",
    "        return numeric.iloc[0:0]",
    "    valid = numeric.iloc[valid_positions]",
    "    gap_candidates = []",
    "    cadence_ns = None",
    "    gap_threshold_ns = None",
    "    time_values_ns = None",
    "    if isinstance(valid.index, pd.DatetimeIndex) and len(valid) > 1:",
    "        time_values_ns = np.array([timestamp.value for timestamp in valid.index], dtype=np.int64)",
    "        deltas_ns = np.diff(time_values_ns)",
    "        positive = deltas_ns[deltas_ns > 0]",
    "        if len(positive) > 0:",
    "            cadence_ns = float(np.median(positive))",
    "            gap_threshold_ns = _robust_gap_threshold_ns(valid.index, gap_factor=gap_factor)",
    "    for valid_index in range(1, len(valid_positions)):",
    "        left_position = int(valid_positions[valid_index - 1])",
    "        right_position = int(valid_positions[valid_index])",
    "        explicit_gap = not isinstance(valid.index, pd.DatetimeIndex) and right_position - left_position > 1",
    "        time_gap = False",
    "        gap_size = float(right_position - left_position)",
    "        if cadence_ns is not None and gap_threshold_ns is not None and time_values_ns is not None:",
    "            delta_ns = float(time_values_ns[valid_index] - time_values_ns[valid_index - 1])",
    "            time_gap = delta_ns > gap_threshold_ns",
    "            gap_size = max(gap_size, delta_ns / cadence_ns)",
    "        if explicit_gap or time_gap:",
    "            gap_candidates.append((valid_index, gap_size))",
    "    # Each retained gap costs one NaN marker and creates another segment; keep",
    "    # a four-value M4 budget per segment: 4*(gaps+1)+gaps <= max_points.",
    "    max_gaps = max(0, min(len(gap_candidates), (max_points - 4) // 5)) if max_points >= 4 else 0",
    "    selected_gaps = sorted(index for index, _size in sorted(gap_candidates, key=lambda row: row[1], reverse=True)[:max_gaps])",
    "    boundaries = [0] + selected_gaps + [len(valid)]",
    "    segments = [valid.iloc[boundaries[i]:boundaries[i + 1]] for i in range(len(boundaries) - 1)]",
    "    value_budget = max(1, max_points - len(selected_gaps))",
    "    segment_floor = min(4, value_budget)",
    "    allocations = [min(segment_floor, len(segment)) for segment in segments]",
    "    remaining = value_budget - sum(allocations)",
    "    lengths = np.array([len(segment) for segment in segments], dtype=float)",
    "    if remaining > 0 and lengths.sum() > 0:",
    "        shares = remaining * lengths / lengths.sum()",
    "        additions = np.floor(shares).astype(int)",
    "        allocations = [allocation + int(addition) for allocation, addition in zip(allocations, additions)]",
    "        leftover = remaining - int(additions.sum())",
    "        for index in np.argsort(-(shares - additions))[:leftover]:",
    "            allocations[int(index)] += 1",
    "    sampled_segments = [downsample_timeseries(segment, max_points=allocation) for segment, allocation in zip(segments, allocations)]",
    "    parts = []",
    "    for index, segment in enumerate(sampled_segments):",
    "        if index > 0:",
    "            left_index = sampled_segments[index - 1].index[-1]",
    "            right_index = segment.index[0]",
    "            if isinstance(valid.index, pd.DatetimeIndex):",
    "                marker_index = left_index + (right_index - left_index) / 2",
    "            elif isinstance(left_index, (int, float, np.integer, np.floating)) and isinstance(right_index, (int, float, np.integer, np.floating)):",
    "                marker_index = (left_index + right_index) / 2",
    "            else:",
    "                marker_index = right_index",
    "            parts.append(pd.Series([np.nan], index=[marker_index], name=series.name))",
    "        parts.append(segment)",
    "    return pd.concat(parts).sort_index().rename(series.name)",
    "",
    "def series_short_label(label):",
    "    # Prefer the entity side of metric:entity labels; otherwise use the final token.",
    "    if not label:",
    "        return label",
    "    text = str(label)",
    "    if ':' in text:",
    "        entity = text.split(':', 1)[1]",
    "        if entity:",
    "            return entity",
    "    if re.fullmatch(r'[A-Za-z][A-Za-z0-9]*[-_]\\d+', text):",
    "        return text",
    "    return re.split(r'[-_]', text)[-1]",
    "",
    "def series_display_label(label):",
    "    # Keep equipment identity in panel titles; a metric suffix such as CHWST is not an identity.",
    "    if label is None:",
    "        return ''",
    "    text = str(label)",
    "    if ':' in text:",
    "        entity = text.split(':', 1)[1].strip()",
    "        if entity:",
    "            return entity.replace('_', '-')",
    "    match = re.search(r'\\b([A-Za-z]{2,})[-_](?:L\\d+[-_])?0*(\\d+)(?:[-_]|$)', text, flags=re.IGNORECASE)",
    "    if match:",
    "        return f'{match.group(1).upper()}-{int(match.group(2)):02d}'",
    "    return text",
    "",
    "def _unique_series_display_labels(columns):",
    "    bases = [series_display_label(column) for column in columns]",
    "    counts = {base: bases.count(base) for base in set(bases)}",
    "    return [base if counts.get(base, 0) == 1 else str(column) for column, base in zip(columns, bases)]",
    "",
    "def build_combined_frame(series_dict=None, value_col='value_num'):",
    "    if series_dict is None:",
    "        series_dict = load_all_series()",
    "    parts = []",
    "    for label, df in sorted(series_dict.items(), key=lambda item: _natural_sort_key(item[0])):",
    "        if df is None or value_col not in df.columns:",
    "            parts.append(pd.Series(dtype=float, name=str(label)))",
    "            continue",
    "        # A manifest label/series key is the stable identity. Short suffixes are",
    "        # lookup aliases only and must never become lossy DataFrame identities.",
    "        col = df[value_col].rename(str(label))",
    "        parts.append(col)",
    "    if not parts:",
    "        return pd.DataFrame()",
    "    return pd.concat(parts, axis=1, sort=False).sort_index()",
    "",
    "def col_series(combined, *names):",
    "    # Match full manifest label or short suffix; return empty Series if not found (no KeyError).",
    "    empty = pd.Series(dtype=float)",
    "    if combined is None or getattr(combined, 'empty', True):",
    "        return empty",
    "    for name in names:",
    "        if name in combined.columns:",
    "            return combined[name]",
    "        short = series_short_label(name)",
    "        if short in combined.columns:",
    "            return combined[short]",
    "        matches = [col for col in combined.columns if col == name or series_short_label(col) == short]",
    "        if len(matches) == 1:",
    "            return combined[matches[0]]",
    "    return empty",
    "",
    "def normalize_status(series):",
    "    s = pd.to_numeric(series, errors='coerce')",
    "    if s.notna().any():",
    "        return (s.fillna(0) > 0).astype(int)",
    "    text = series.astype(str).str.strip().str.upper()",
    "    on_tokens = {'ON', 'TRUE', 'YES', 'RUN', 'RUNNING', '1'}",
    "    return text.isin(on_tokens).astype(int)",
    "",
    "def resample_status_15m(df, value_col='value_num'):",
    "    if df is None or df.empty or value_col not in df.columns:",
    "        return pd.Series(dtype=int)",
    "    status = normalize_status(df[value_col])",
    "    return status.resample('15min').max().ffill().fillna(0).astype(int)",
    "",
    `COLOR_CYCLE = [${colors}]`,
    `LINE_STYLE_CYCLE = [${lineStyles}]`,
    "",
    "def chart_color(i):",
    "    return COLOR_CYCLE[int(i) % len(COLOR_CYCLE)]",
    "",
    "def chart_linestyle(i):",
    "    return LINE_STYLE_CYCLE[int(i) % len(LINE_STYLE_CYCLE)]",
    "",
    "def data_coverage(frame):",
    "    if frame is None or getattr(frame, 'empty', True):",
    "        return pd.Series(dtype=int)",
    "    return frame.notna().sum()",
    "",
    "def plot_series(ax, data, col=None, *, color=None, label=None, color_index=None, linewidth=2.0, marker_if_le=12, **kwargs):",
    "    # Default timeseries: preserve long/explicit gaps and cap plotted points at 1000.",
    "    if isinstance(data, pd.Series):",
    "        series = data",
    "        use_label = label or (str(data.name) if data.name else 'series')",
    "    elif isinstance(data, pd.DataFrame):",
    "        if col is None or col not in data.columns:",
    "            return None",
    "        series = data[col]",
    "        use_label = label or str(col)",
    "    else:",
    "        return None",
    "    if series.dropna().empty:",
    "        return None",
    "    series = _series_with_gap_breaks(series, max_points=1000)",
    "    style_index = len(ax.get_lines()) if color_index is None else int(color_index)",
    "    use_color = color if color is not None else chart_color(style_index)",
    "    plot_kw = {'label': use_label, 'color': use_color, 'linewidth': linewidth}",
    "    if 'linestyle' not in kwargs:",
    "        plot_kw['linestyle'] = chart_linestyle(style_index)",
    "    if len(series) <= marker_if_le:",
    "        plot_kw['marker'] = 'o'",
    "        plot_kw['markersize'] = 3",
    "    return ax.plot(series.index, series.values, **plot_kw, **kwargs)[0]",
    "",
    "def _is_long_history(frame, minimum_days=7):",
    "    if frame is None or getattr(frame, 'empty', True) or not isinstance(frame.index, pd.DatetimeIndex):",
    "        return False",
    "    valid_index = frame.index[~frame.index.isna()]",
    "    return len(valid_index) > 1 and (valid_index.max() - valid_index.min()) >= pd.Timedelta(days=minimum_days)",
    "",
    "def _hourly_series_profile(series):",
    "    numeric = pd.to_numeric(series, errors='coerce').replace([np.inf, -np.inf], np.nan).dropna().sort_index()",
    "    if numeric.empty or not isinstance(numeric.index, pd.DatetimeIndex):",
    "        return pd.DataFrame(columns=['median', 'p10', 'p90'])",
    "    numeric.index = numeric.index.tz_localize('UTC').tz_convert(HKT) if numeric.index.tz is None else numeric.index.tz_convert(HKT)",
    "    hourly = numeric.resample('1h')",
    "    return pd.DataFrame({",
    "        'median': hourly.median(),",
    "        'p10': hourly.quantile(0.10),",
    "        'p90': hourly.quantile(0.90)",
    "    })",
    "",
    "def _small_multiples_share_y(series_values, disparity_factor=4.0):",
    "    robust_ranges = []",
    "    for values in series_values:",
    "        numeric = pd.to_numeric(values, errors='coerce').dropna()",
    "        if numeric.empty:",
    "            continue",
    "        low = float(numeric.quantile(0.05))",
    "        high = float(numeric.quantile(0.95))",
    "        robust_ranges.append((low, high))",
    "    if len(robust_ranges) < 2:",
    "        return True",
    "    spans = [max(0.0, high - low) for low, high in robust_ranges]",
    "    global_span = max(high for _low, high in robust_ranges) - min(low for low, _high in robust_ranges)",
    "    typical_span = float(np.median(spans))",
    "    if typical_span <= 1e-12:",
    "        centers = [0.5 * (low + high) for low, high in robust_ranges]",
    "        typical_level = float(np.median(np.abs(centers)))",
    "        return global_span <= max(typical_level, 1e-12)",
    "    return global_span <= max(typical_span * disparity_factor, 1e-12)",
    "",
    "def plot_series_small_multiples(data, *, title, ylabel=None, subtitle=None, sharey='auto'):",
    "    if data is None or not isinstance(data, pd.DataFrame):",
    "        data = pd.DataFrame()",
    "    columns = sorted(list(data.columns), key=_natural_sort_key)",
    "    count = len(columns)",
    "    ncols = 4 if count >= 7 else 3 if count >= 5 else max(1, min(2, count))",
    "    nrows = max(1, int(np.ceil(max(1, count) / ncols)))",
    "    long_history = _is_long_history(data)",
    "    profiles = {column: _hourly_series_profile(data[column]) for column in columns} if long_history else {}",
    "    # Match Matplotlib's visible envelope: an extreme P10/P90 band can flatten",
    "    # every other panel even when all hourly medians are comparable.",
    "    scale_values = [pd.Series([profiles[column]['p10'].min(), profiles[column]['p90'].max()]) if long_history and not profiles[column].empty else data[column] for column in columns]",
    "    use_shared_y = _small_multiples_share_y(scale_values) if sharey == 'auto' else bool(sharey)",
    "    apply_scientific_style()",
    "    fig_width = max(8.0, 3.15 * ncols)",
    "    fig_height = max(4.8, 3.05 * nrows + 0.7)",
    "    fig, axes = plt.subplots(nrows, ncols, figsize=(fig_width, fig_height), sharex=True, sharey=use_shared_y, squeeze=False, layout='constrained')",
    "    # Keep a stable header band inside the canvas so the subtitle cannot touch the first row.",
    "    fig.get_layout_engine().set(rect=(0.0, 0.0, 1.0, 0.88))",
    "    fig.patch.set_facecolor('#F8FAFC')",
    "    flat_axes = list(axes.flatten())",
    "    display_labels = _unique_series_display_labels(columns)",
    "    for index, (column, display_label) in enumerate(zip(columns, display_labels)):",
    "        ax = flat_axes[index]",
    "        style_chart_axes(ax)",
    "        color = chart_color(index)",
    "        if long_history:",
    "            profile = profiles[column]",
    "            finite = profile[['median', 'p10', 'p90']].notna().all(axis=1) if not profile.empty else pd.Series(dtype=bool)",
    "            if finite.any():",
    "                ax.fill_between(profile.index, profile['p10'].to_numpy(dtype=float), profile['p90'].to_numpy(dtype=float), where=finite.to_numpy(dtype=bool), color=color, alpha=0.16, linewidth=0)",
    "                marker_kw = {'marker': 'o', 'markersize': 3} if int(finite.sum()) <= 12 else {}",
    "                ax.plot(profile.index, profile['median'].to_numpy(dtype=float), color=color, linewidth=1.8, **marker_kw)",
    "            else:",
    "                ax.text(0.5, 0.5, 'No valid samples', transform=ax.transAxes, ha='center', va='center', color='#64748B')",
    "        else:",
    "            line = plot_series(ax, data, column, color=color, label=display_label, color_index=index)",
    "            if line is None:",
    "                ax.text(0.5, 0.5, 'No valid samples', transform=ax.transAxes, ha='center', va='center', color='#64748B')",
    "        ax.set_title(display_label, loc='left', pad=8, fontsize=11, fontweight='600', color='#0F172A')",
    "        _format_small_multiples_hkt_axis(ax, data.index)",
    "        ax.set_xlabel('')",
    "        if index // ncols < nrows - 1:",
    "            ax.tick_params(axis='x', labelbottom=False)",
    "    for ax in flat_axes[count:]:",
    "        ax.set_visible(False)",
    "    scale_note = 'shared y-scale' if use_shared_y else 'independent y-scales due to range disparity'",
    "    valid_index = data.index[~data.index.isna()] if isinstance(data.index, pd.DatetimeIndex) else data.index",
    "    date_note = ''",
    "    if len(valid_index) > 0 and isinstance(data.index, pd.DatetimeIndex):",
    "        start_hkt = valid_index.min().tz_localize('UTC').tz_convert(HKT) if valid_index.tz is None else valid_index.min().tz_convert(HKT)",
    "        end_hkt = valid_index.max().tz_localize('UTC').tz_convert(HKT) if valid_index.tz is None else valid_index.max().tz_convert(HKT)",
    "        date_note = f\"{start_hkt.strftime('%d %b')}–{end_hkt.strftime('%d %b %Y')}\"",
    "    aggregation_note = 'Hourly median with P10-P90 band · HKT' if long_history else 'Raw samples · HKT'",
    "    chart_subtitle = ' · '.join(part for part in [subtitle, aggregation_note, date_note, scale_note] if part)",
    "    fig.suptitle(title, x=0.02, y=0.985, ha='left', fontsize=16, fontweight='600', color='#0F172A')",
    "    fig.text(0.02, 0.94, chart_subtitle, ha='left', va='top', fontsize=10, color='#64748B')",
    "    fig.supxlabel('Time (HKT)', fontsize=11, color='#64748B')",
    "    if ylabel:",
    "        fig.supylabel(ylabel, fontsize=11, color='#64748B')",
    "    return fig, axes",
    "",
    "def plot_timeseries_default(data, *, title, ylabel=None, subtitle=None, layout='auto'):",
    "    if data is None or not isinstance(data, pd.DataFrame):",
    "        data = pd.DataFrame()",
    "    columns = sorted(list(data.columns), key=_natural_sort_key)",
    "    if layout not in {'auto', 'overlay', 'small_multiples'}:",
    "        raise ValueError(\"layout must be 'auto', 'overlay', or 'small_multiples'\")",
    "    use_small_multiples = layout == 'small_multiples' or (layout == 'auto' and 5 <= len(columns) <= 8 and _is_long_history(data))",
    "    if use_small_multiples:",
    "        return plot_series_small_multiples(data, title=title, ylabel=ylabel, subtitle=subtitle)",
    "    fig, ax = new_figure()",
    "    set_chart_title(ax, title, subtitle=subtitle, ylabel=ylabel)",
    "    for index, column in enumerate(columns):",
    "        plot_series(ax, data, column, color_index=index)",
    "    format_hkt_axis(ax)",
    "    finalize_legend(ax)",
    "    return fig, ax",
    "",
    "def plot_status_step(ax, data, col=None, *, color='orange', alpha=0.25, label=None, **kwargs):",
    "    # Discrete status only (Run_Status, S, etc.) — step fill, not for analog signals.",
    "    if isinstance(data, pd.DataFrame):",
    "        if col is None or col not in data.columns:",
    "            return None",
    "        series = normalize_status(data[col]).dropna()",
    "        use_label = label or str(col)",
    "    elif isinstance(data, pd.Series):",
    "        series = normalize_status(data).dropna()",
    "        use_label = label or (str(data.name) if data.name else 'status')",
    "    else:",
    "        return None",
    "    if series.empty:",
    "        return None",
    "    return ax.fill_between(series.index, 0, series.values, step='post', alpha=alpha, color=color, label=use_label, **kwargs)",
    "",
    "def apply_scientific_style():",
    `    sns.set_theme(style="${SCIENTIFIC_CHART_CONSTANTS.themeStyle}", context="${SCIENTIFIC_CHART_CONSTANTS.themeContext}", palette="${SCIENTIFIC_CHART_CONSTANTS.palette}")`,
    "    plt.rcParams.update({",
    `        'figure.facecolor': '${SCIENTIFIC_CHART_CONSTANTS.figureFacecolor}',`,
    `        'axes.facecolor': '${SCIENTIFIC_CHART_CONSTANTS.axesFacecolor}',`,
    `        'axes.edgecolor': '${SCIENTIFIC_CHART_CONSTANTS.spineColor}',`,
    `        'axes.labelcolor': '${SCIENTIFIC_CHART_CONSTANTS.mutedTextColor}',`,
    `        'text.color': '${SCIENTIFIC_CHART_CONSTANTS.textColor}',`,
    `        'xtick.color': '${SCIENTIFIC_CHART_CONSTANTS.mutedTextColor}',`,
    `        'ytick.color': '${SCIENTIFIC_CHART_CONSTANTS.mutedTextColor}',`,
    "        'axes.linewidth': 0.9,",
    "        'axes.titleweight': '600',",
    "        'axes.titlesize': 13,",
    "        'axes.labelsize': 11,",
    "        'font.size': 11,",
    "        'legend.fontsize': 10,",
    "        'xtick.labelsize': 10,",
    "        'ytick.labelsize': 10,",
    "        'grid.color': '#E2E8F0',",
    "        'grid.linewidth': 0.7,",
    "        'grid.alpha': 0.9,",
    "        'lines.linewidth': 2.0,",
    "        'font.family': 'sans-serif',",
    "    })",
    "",
    "def style_chart_axes(ax):",
    "    ax.set_facecolor('#FFFFFF')",
    "    ax.grid(True, linestyle='-', linewidth=0.7, alpha=0.85, color='#E2E8F0')",
    "    ax.set_axisbelow(True)",
    "    ax.spines['top'].set_visible(False)",
    "    ax.spines['right'].set_visible(False)",
    "    ax.spines['left'].set_color('#CBD5E1')",
    "    ax.spines['bottom'].set_color('#CBD5E1')",
    "",
    "def set_chart_title(ax, title, *, subtitle=None, xlabel=None, ylabel=None):",
    "    # Reserve a second text row only when a subtitle is present.",
    "    title_pad = 34 if subtitle else 14",
    "    ax.set_title(title, loc='left', pad=title_pad, fontsize=13, fontweight='600', color='#0F172A')",
    "    if subtitle:",
    "        ax.text(0, 1.015, subtitle, transform=ax.transAxes, fontsize=10, color='#64748B', va='bottom')",
    "    if xlabel:",
    "        ax.set_xlabel(xlabel, labelpad=8)",
    "    if ylabel:",
    "        ax.set_ylabel(ylabel, labelpad=8)",
    "",
    "def finalize_legend(ax, *, loc=None, ncol=None):",
    "    handles, labels = ax.get_legend_handles_labels()",
    "    if not labels:",
    "        return None",
    "    legend_kw = {'frameon': True, 'framealpha': 0.95, 'edgecolor': '#E2E8F0',",
    "                 'facecolor': '#FFFFFF', 'borderpad': 0.6, 'labelspacing': 0.5}",
    "    if len(labels) >= 5 and loc is None:",
    "        # Four-column legend below the axes keeps long fleet labels off the data.",
    "        return ax.legend(handles, labels, loc='upper center', bbox_to_anchor=(0.5, -0.18),",
    "                         ncol=ncol or min(4, len(labels)), columnspacing=1.2, **legend_kw)",
    "    return ax.legend(handles, labels, loc=loc or 'best', ncol=ncol or 1, **legend_kw)",
    "",
    "def new_figure(nrows=1, ncols=1, figsize=None):",
    "    apply_scientific_style()",
    `    if figsize is None:`,
    `        figsize = (${figW}, ${figH})`,
    `    fig, axes = plt.subplots(nrows, ncols, figsize=figsize, layout='constrained')`,
    `    fig.patch.set_facecolor('${SCIENTIFIC_CHART_CONSTANTS.figureFacecolor}')`,
    "    if hasattr(axes, 'flatten'):",
    "        for ax in axes.flatten():",
    "            style_chart_axes(ax)",
    "    else:",
    "        style_chart_axes(axes)",
    "    return fig, axes",
    "",
    "def format_hkt_axis(ax, minticks=4, maxticks=10):",
    "    locator = mdates.AutoDateLocator(tz=HKT, minticks=minticks, maxticks=maxticks)",
    "    formatter = mdates.ConciseDateFormatter(locator, tz=HKT)",
    "    ax.xaxis.set_major_locator(locator)",
    "    ax.xaxis.set_major_formatter(formatter)",
    "    for label in ax.get_xticklabels():",
    "        label.set_rotation(30)",
    "        label.set_horizontalalignment('right')",
    "    ax.set_xlabel('Time (HKT)', labelpad=8)",
    "",
    "def _format_small_multiples_hkt_axis(ax, index):",
    "    locator = mdates.AutoDateLocator(tz=HKT, minticks=3, maxticks=5)",
    "    span = (index.max() - index.min()) if isinstance(index, pd.DatetimeIndex) and len(index) > 1 else pd.Timedelta(0)",
    "    date_format = '%b %Y' if span >= pd.Timedelta(days=180) else '%d %b' if span >= pd.Timedelta(days=2) else '%H:%M'",
    "    ax.xaxis.set_major_locator(locator)",
    "    ax.xaxis.set_major_formatter(mdates.DateFormatter(date_format, tz=HKT))",
    "    ax.xaxis.get_offset_text().set_visible(False)",
    "    for label in ax.get_xticklabels():",
    "        label.set_rotation(30)",
    "        label.set_horizontalalignment('right')",
    "",
    "def save_chart(fig, filename):",
    "    output_dir = os.environ.get('OUTPUT_DIR', '.')",
    "    os.makedirs(output_dir, exist_ok=True)",
    "    if not filename.endswith('.png'):",
    "        filename = filename + '.png'",
    "    abs_path = os.path.join(output_dir, filename)",
    `    fig.savefig(abs_path, dpi=${dpi}, bbox_inches='tight', facecolor='${SCIENTIFIC_CHART_CONSTANTS.figureFacecolor}', edgecolor='none', pad_inches=0.25)`,
    "    plt.close(fig)",
    "    return os.path.join('outputs', filename)",
    ""
  ].join("\n");
}
