/** Single source of truth for enterprise chart styling and execute_code data/chart helpers. */

export const SCIENTIFIC_CHART_CONSTANTS = {
  figsize: [11, 6.5] as const,
  dpi: 300,
  palette: "deep",
  themeStyle: "whitegrid",
  themeContext: "talk",
  figureFacecolor: "#F8FAFC",
  axesFacecolor: "#FFFFFF",
  gridColor: "#E2E8F0",
  textColor: "#0F172A",
  mutedTextColor: "#64748B",
  spineColor: "#CBD5E1"
} as const;

/** Corporate presentation palette — saturated enough for slides, still distinguishable. */
export const COLOR_CYCLE = [
  "#2563EB",
  "#0D9488",
  "#7C3AED",
  "#D97706",
  "#E11D48",
  "#475569"
] as const;

const DATA_BRIDGE_MINIMAL_EXAMPLE = [
  "combined = build_combined_frame()",
  "fig, ax = new_figure()",
  "set_chart_title(ax, 'Plant overview', ylabel='Value')",
  "for i, col in enumerate(combined.columns): plot_series(ax, combined, col, color_index=i)",
  "format_hkt_axis(ax)",
  "finalize_legend(ax)",
  "path = save_chart(fig, 'overview.png')"
].join("; ");

export function dataBridgeSkillHint(): string {
  return [
    "TOOL DATA BRIDGE (mandatory for execute_code after data tools):",
    "1) load_all_series() returns {label: DataFrame} — iterate `for label, df in load_all_series().items()`; NEVER `for entry in load_all_series()` (entry is a string key, not a manifest dict).",
    "2) Prefer build_combined_frame() for a wide HKT-indexed table; use manifest label or col_series(combined, label) — never guess column names like combined['short_name'].",
    "3) Helpers: load_series_by_label, items_to_frame, downsample_timeseries (first/min/max/last, <=1000 points), normalize_status, resample_status_15m, series_short_label.",
    "4) Do NOT open outputs/.tool_cache/*_manifest.json by hand.",
    "5) pandas 3: .ffill()/.bfill(); never fillna(method=...); pd.concat(..., sort=False).",
    "6) One execute_code pass ending in save_chart — no debug-only scripts (print columns/shape only).",
    "7) Before plotting: data_coverage(combined) — skip or note columns with 0 valid points; wide table rows are sparse (outer join).",
    "8) With request-local history, stdout/stderr are always hidden; non-image artifacts are hidden. Do not print data or summaries; return results through saved charts only.",
    `Minimal pattern: ${DATA_BRIDGE_MINIMAL_EXAMPLE}`
  ].join(" ");
}

export function scientificChartSkillHint(): string {
  const [w, h] = SCIENTIFIC_CHART_CONSTANTS.figsize;
  return [
    "ENTERPRISE CHARTS (mandatory for any figure — fixed presentation style for corporate reports):",
    `Use new_figure(), set_chart_title(ax, title, ylabel=...), plot_series(), chart_color(i), format_hkt_axis(ax), finalize_legend(ax), save_chart(fig, filename) — dpi=${SCIENTIFIC_CHART_CONSTANTS.dpi}, figsize=(${w}, ${h}).`,
    "Style is auto-applied (whitegrid, corporate palette, left-aligned title, clean spines) — do NOT customize colors/fonts manually.",
    "DEFAULT timeseries = line chart: plot_series(ax, combined, col) drops NaN and breaks lines at gaps — do NOT interpolate/fill_between across missing spans by default.",
    "Use plot_status_step(ax, combined, col) only for discrete status (Run_Status/S); never fill_between on power/temperature/flow.",
    "NEVER hard-code COLOR_CYCLE[6] — use chart_color(i) or COLOR_CYCLE[i % len(COLOR_CYCLE)].",
    "mdates is pre-imported — use format_hkt_axis(ax); never mdates.DateFormatter(..., tz=...).",
    "Do NOT sns.set_style/set_theme with custom palettes; do NOT plt.savefig directly.",
    "English-only on-chart text; every chart needs set_chart_title() with a clear business title; every chart script must call save_chart()."
  ].join(" ");
}

/** Detect chart intent without save_chart output — for execute_code sanity check. */
export function chartSanityViolation(userCode: string, newPngCount: number): string | null {
  const trimmed = userCode.trim();
  if (!trimmed) {
    return null;
  }
  const chartIntent =
    /\bnew_figure\s*\(|\bplot_series\s*\(|\bplt\.subplots\s*\(|\bplt\.plot\s*\(|\b\.plot\s*\(|\baxes\[\d+\]\.plot\s*\(/i.test(trimmed);
  if (/\bsave_chart\s*\(/i.test(trimmed) || newPngCount > 0) {
    return null;
  }
  const debugOnly =
    /\bprint\s*\(/i.test(trimmed)
    && /\b(build_combined_frame|load_all_series|\.columns|\.shape|data_coverage)\b/i.test(trimmed);
  if (debugOnly && !chartIntent) {
    return "Debug-only execute_code (print columns/shape/coverage) is not allowed after data tools. One pass ending in save_chart().";
  }
  if (chartIntent) {
    return "Chart code detected but save_chart() was not called and no PNG was generated. End chart scripts with save_chart(fig, 'name.png').";
  }
  return null;
}

export function executeCodeInjectedHeader(): string {
  const [figW, figH] = SCIENTIFIC_CHART_CONSTANTS.figsize;
  const dpi = SCIENTIFIC_CHART_CONSTANTS.dpi;
  const colors = COLOR_CYCLE.map((c) => `"${c}"`).join(", ");

  return [
    "# Auto-injected by BuildingAgent execute_code",
    "import json, os, re",
    "from zoneinfo import ZoneInfo",
    "import pandas as pd",
    "import numpy as np",
    "import matplotlib",
    "matplotlib.use('Agg')",
    "import matplotlib.pyplot as plt",
    "import matplotlib.dates as mdates",
    "import seaborn as sns",
    'HKT = ZoneInfo("Asia/Hong_Kong")',
    "",
    "def load_tool_manifest():",
    "    # entries: [{label, data_file, tool, toolCallId}] — use entry['label'], not entry['name']",
    "    path = os.environ.get('TOOL_CACHE_MANIFEST', '')",
    "    if path and os.path.isfile(path):",
    "        with open(path, encoding='utf-8') as f:",
    "            return json.load(f)",
    "    return {'requestId': os.environ.get('REQUEST_ID', ''), 'entries': []}",
    "",
    "def load_cached_items(data_file, data_key=None):",
    "    with open(data_file, encoding='utf-8') as f:",
    "        payload = json.load(f)",
    "    if isinstance(payload, dict) and isinstance(payload.get('series'), list):",
    "        candidates = payload['series']",
    "        if data_key:",
    "            payload = next((row for row in candidates if isinstance(row, dict) and (row.get('data_key') == data_key or row.get('instanceId') == data_key or row.get('instance_id') == data_key)), {})",
    "        elif len(candidates) == 1:",
    "            payload = candidates[0]",
    "    if isinstance(payload, dict):",
    "        return payload.get('items', payload.get('history', payload))",
    "    return payload",
    "",
    "def items_to_frame(items, value_col='value_num'):",
    "    df = pd.DataFrame(items)",
    "    if df.empty:",
    "        return df",
    "    aliases = {'valueNum': 'value_num', 'valueText': 'value_text', 'instanceId': 'instance_id'}",
    "    rename = {source: target for source, target in aliases.items() if source in df.columns and target not in df.columns}",
    "    if rename:",
    "        df = df.rename(columns=rename)",
    "    if 'ts' in df.columns:",
    "        df['ts'] = pd.to_datetime(df['ts'], utc=True).dt.tz_convert(HKT)",
    "        df = df.set_index('ts').sort_index()",
    "    if value_col in df.columns:",
    "        df[value_col] = pd.to_numeric(df[value_col], errors='coerce')",
    "    return df",
    "",
    "def load_series_by_label(label):",
    "    manifest = load_tool_manifest()",
    "    for entry in manifest.get('entries', []):",
    "        if entry.get('label') == label:",
    "            return items_to_frame(load_cached_items(entry['data_file'], entry.get('data_key')))",
    "    raise KeyError(f'No manifest entry for label={label!r}')",
    "",
    "def load_all_series():",
    "    # Returns dict[str, DataFrame] keyed by manifest label — NOT a list of entries.",
    "    out = {}",
    "    for entry in load_tool_manifest().get('entries', []):",
    "        label = entry.get('label') or entry.get('data_key')",
    "        if not label:",
    "            continue",
    "        unique_label = label",
    "        if unique_label in out:",
    "            unique_label = f\"{label}:{entry.get('data_key') or entry.get('toolCallId', len(out))}\"",
    "        out[unique_label] = items_to_frame(load_cached_items(entry['data_file'], entry.get('data_key')))",
    "    return out",
    "",
    "def downsample_timeseries(data, value_col='value_num', max_points=1000):",
    "    # Preserve the first/min/max/last valid value of each chronological bucket.",
    "    if data is None or max_points <= 0:",
    "        return data",
    "    is_series = isinstance(data, pd.Series)",
    "    if is_series:",
    "        frame = data.to_frame(name=data.name or value_col)",
    "        numeric_col = frame.columns[0]",
    "    elif isinstance(data, pd.DataFrame) and value_col in data.columns:",
    "        frame = data",
    "        numeric_col = value_col",
    "    else:",
    "        return data",
    "    numeric = pd.to_numeric(frame[numeric_col], errors='coerce')",
    "    valid_positions = np.flatnonzero(numeric.notna().to_numpy())",
    "    if len(frame) <= max_points:",
    "        return data",
    "    if len(valid_positions) <= max_points:",
    "        sampled = frame.iloc[valid_positions].sort_index()",
    "        return sampled.iloc[:, 0].rename(data.name) if is_series else sampled",
    "    if max_points < 4:",
    "        selected = valid_positions[np.linspace(0, len(valid_positions) - 1, max_points, dtype=int)]",
    "    else:",
    "        bucket_count = max(1, max_points // 4)",
    "        selected_positions = []",
    "        edges = np.linspace(0, len(valid_positions), bucket_count + 1, dtype=int)",
    "        for bucket in range(bucket_count):",
    "            bucket_positions = valid_positions[edges[bucket]:edges[bucket + 1]]",
    "            if len(bucket_positions) == 0:",
    "                continue",
    "            bucket_values = numeric.iloc[bucket_positions].to_numpy(dtype=float)",
    "            selected_positions.extend([",
    "                int(bucket_positions[0]),",
    "                int(bucket_positions[int(np.nanargmin(bucket_values))]),",
    "                int(bucket_positions[int(np.nanargmax(bucket_values))]),",
    "                int(bucket_positions[-1])",
    "            ])",
    "        selected = np.array(sorted(set(selected_positions)), dtype=int)",
    "        if len(selected) > max_points:",
    "            selected = selected[np.linspace(0, len(selected) - 1, max_points, dtype=int)]",
    "    sampled = frame.iloc[selected].sort_index()",
    "    return sampled.iloc[:, 0].rename(data.name) if is_series else sampled",
    "",
    "def _series_with_gap_breaks(series, max_points=1000, gap_factor=1.5):",
    "    # Split before sampling so long/explicit gaps remain disconnected after reduction.",
    "    numeric = pd.to_numeric(series, errors='coerce')",
    "    valid_positions = np.flatnonzero(numeric.notna().to_numpy())",
    "    if len(valid_positions) == 0:",
    "        return numeric.iloc[0:0]",
    "    valid = numeric.iloc[valid_positions]",
    "    gap_candidates = []",
    "    cadence_ns = None",
    "    time_values_ns = None",
    "    if isinstance(valid.index, pd.DatetimeIndex) and len(valid) > 1:",
    "        time_values_ns = np.array([timestamp.value for timestamp in valid.index], dtype=np.int64)",
    "        deltas_ns = np.diff(time_values_ns)",
    "        positive = deltas_ns[deltas_ns > 0]",
    "        if len(positive) > 0:",
    "            cadence_ns = float(np.median(positive))",
    "    for valid_index in range(1, len(valid_positions)):",
    "        left_position = int(valid_positions[valid_index - 1])",
    "        right_position = int(valid_positions[valid_index])",
    "        explicit_gap = not isinstance(valid.index, pd.DatetimeIndex) and right_position - left_position > 1",
    "        time_gap = False",
    "        gap_size = float(right_position - left_position)",
    "        if cadence_ns is not None and time_values_ns is not None:",
    "            delta_ns = float(time_values_ns[valid_index] - time_values_ns[valid_index - 1])",
    "            time_gap = delta_ns > cadence_ns * gap_factor",
    "            gap_size = max(gap_size, delta_ns / cadence_ns)",
    "        if explicit_gap or time_gap:",
    "            gap_candidates.append((valid_index, gap_size))",
    "    max_gaps = max(0, min(len(gap_candidates), (max_points - 1) // 2))",
    "    selected_gaps = sorted(index for index, _size in sorted(gap_candidates, key=lambda row: row[1], reverse=True)[:max_gaps])",
    "    boundaries = [0] + selected_gaps + [len(valid)]",
    "    segments = [valid.iloc[boundaries[i]:boundaries[i + 1]] for i in range(len(boundaries) - 1)]",
    "    value_budget = max(1, max_points - len(selected_gaps))",
    "    base = 4 if value_budget >= 4 * len(segments) else 1",
    "    allocations = [base] * len(segments)",
    "    remaining = value_budget - sum(allocations)",
    "    lengths = np.array([len(segment) for segment in segments], dtype=float)",
    "    if remaining > 0 and lengths.sum() > 0:",
    "        shares = remaining * lengths / lengths.sum()",
    "        additions = np.floor(shares).astype(int)",
    "        allocations = [allocation + int(addition) for allocation, addition in zip(allocations, additions)]",
    "        leftover = remaining - int(additions.sum())",
    "        for index in np.argsort(-(shares - additions))[:leftover]:",
    "            allocations[int(index)] += 1",
    "    sampled_segments = [downsample_timeseries(segment, max_points=allocation) for segment, allocation in zip(segments, allocations)]",
    "    parts = []",
    "    for index, segment in enumerate(sampled_segments):",
    "        if index > 0:",
    "            left_index = sampled_segments[index - 1].index[-1]",
    "            right_index = segment.index[0]",
    "            if isinstance(valid.index, pd.DatetimeIndex):",
    "                marker_index = left_index + (right_index - left_index) / 2",
    "            elif isinstance(left_index, (int, float, np.integer, np.floating)) and isinstance(right_index, (int, float, np.integer, np.floating)):",
    "                marker_index = (left_index + right_index) / 2",
    "            else:",
    "                marker_index = right_index",
    "            parts.append(pd.Series([np.nan], index=[marker_index], name=series.name))",
    "        parts.append(segment)",
    "    return pd.concat(parts).sort_index().rename(series.name)",
    "",
    "def series_short_label(label):",
    "    # Generic: last token after '-' or '_' (e.g. Plant-A-Temp01 -> Temp01). No domain alias map.",
    "    if not label:",
    "        return label",
    "    return re.split(r'[-_]', str(label))[-1]",
    "",
    "def build_combined_frame(series_dict=None, value_col='value_num'):",
    "    if series_dict is None:",
    "        series_dict = load_all_series()",
    "    parts = []",
    "    used_names = set()",
    "    for label, df in series_dict.items():",
    "        if df is None or df.empty or value_col not in df.columns:",
    "            continue",
    "        short = series_short_label(label)",
    "        col_name = short if short not in used_names else label",
    "        used_names.add(col_name)",
    "        col = df[value_col].rename(col_name)",
    "        parts.append(col)",
    "    if not parts:",
    "        return pd.DataFrame()",
    "    return pd.concat(parts, axis=1, sort=False).sort_index()",
    "",
    "def col_series(combined, *names):",
    "    # Match full manifest label or short suffix; return empty Series if not found (no KeyError).",
    "    empty = pd.Series(dtype=float)",
    "    if combined is None or getattr(combined, 'empty', True):",
    "        return empty",
    "    for name in names:",
    "        if name in combined.columns:",
    "            return combined[name]",
    "        short = series_short_label(name)",
    "        if short in combined.columns:",
    "            return combined[short]",
    "        for col in combined.columns:",
    "            if col == name or series_short_label(col) == short:",
    "                return combined[col]",
    "    return empty",
    "",
    "def normalize_status(series):",
    "    s = pd.to_numeric(series, errors='coerce')",
    "    if s.notna().any():",
    "        return (s.fillna(0) > 0).astype(int)",
    "    text = series.astype(str).str.strip().str.upper()",
    "    on_tokens = {'ON', 'TRUE', 'YES', 'RUN', 'RUNNING', '1'}",
    "    return text.isin(on_tokens).astype(int)",
    "",
    "def resample_status_15m(df, value_col='value_num'):",
    "    if df is None or df.empty or value_col not in df.columns:",
    "        return pd.Series(dtype=int)",
    "    status = normalize_status(df[value_col])",
    "    return status.resample('15min').max().ffill().fillna(0).astype(int)",
    "",
    `COLOR_CYCLE = [${colors}]`,
    "",
    "def chart_color(i):",
    "    return COLOR_CYCLE[int(i) % len(COLOR_CYCLE)]",
    "",
    "def data_coverage(frame):",
    "    if frame is None or getattr(frame, 'empty', True):",
    "        return pd.Series(dtype=int)",
    "    return frame.notna().sum()",
    "",
    "def plot_series(ax, data, col=None, *, color=None, label=None, color_index=0, linewidth=2.0, marker_if_le=12, **kwargs):",
    "    # Default timeseries: preserve long/explicit gaps and cap plotted points at 1000.",
    "    if isinstance(data, pd.Series):",
    "        series = data",
    "        use_label = label or (str(data.name) if data.name else 'series')",
    "    elif isinstance(data, pd.DataFrame):",
    "        if col is None or col not in data.columns:",
    "            return None",
    "        series = data[col]",
    "        use_label = label or str(col)",
    "    else:",
    "        return None",
    "    if series.dropna().empty:",
    "        return None",
    "    series = _series_with_gap_breaks(series, max_points=1000)",
    "    use_color = color if color is not None else chart_color(color_index)",
    "    plot_kw = {'label': use_label, 'color': use_color, 'linewidth': linewidth}",
    "    if len(series) <= marker_if_le:",
    "        plot_kw['marker'] = 'o'",
    "        plot_kw['markersize'] = 3",
    "    return ax.plot(series.index, series.values, **plot_kw, **kwargs)[0]",
    "",
    "def plot_status_step(ax, data, col=None, *, color='orange', alpha=0.25, label=None, **kwargs):",
    "    # Discrete status only (Run_Status, S, etc.) — step fill, not for analog signals.",
    "    if isinstance(data, pd.DataFrame):",
    "        if col is None or col not in data.columns:",
    "            return None",
    "        series = normalize_status(data[col]).dropna()",
    "        use_label = label or str(col)",
    "    elif isinstance(data, pd.Series):",
    "        series = normalize_status(data).dropna()",
    "        use_label = label or (str(data.name) if data.name else 'status')",
    "    else:",
    "        return None",
    "    if series.empty:",
    "        return None",
    "    return ax.fill_between(series.index, 0, series.values, step='post', alpha=alpha, color=color, label=use_label, **kwargs)",
    "",
    "def apply_scientific_style():",
    `    sns.set_theme(style="${SCIENTIFIC_CHART_CONSTANTS.themeStyle}", context="${SCIENTIFIC_CHART_CONSTANTS.themeContext}", palette="${SCIENTIFIC_CHART_CONSTANTS.palette}")`,
    "    plt.rcParams.update({",
    `        'figure.facecolor': '${SCIENTIFIC_CHART_CONSTANTS.figureFacecolor}',`,
    `        'axes.facecolor': '${SCIENTIFIC_CHART_CONSTANTS.axesFacecolor}',`,
    `        'axes.edgecolor': '${SCIENTIFIC_CHART_CONSTANTS.spineColor}',`,
    `        'axes.labelcolor': '${SCIENTIFIC_CHART_CONSTANTS.mutedTextColor}',`,
    `        'text.color': '${SCIENTIFIC_CHART_CONSTANTS.textColor}',`,
    `        'xtick.color': '${SCIENTIFIC_CHART_CONSTANTS.mutedTextColor}',`,
    `        'ytick.color': '${SCIENTIFIC_CHART_CONSTANTS.mutedTextColor}',`,
    "        'axes.linewidth': 0.9,",
    "        'axes.titleweight': '600',",
    "        'axes.titlesize': 13,",
    "        'axes.labelsize': 11,",
    "        'font.size': 11,",
    "        'legend.fontsize': 10,",
    "        'xtick.labelsize': 10,",
    "        'ytick.labelsize': 10,",
    "        'grid.color': '#E2E8F0',",
    "        'grid.linewidth': 0.7,",
    "        'grid.alpha': 0.9,",
    "        'lines.linewidth': 2.0,",
    "        'font.family': 'sans-serif',",
    "    })",
    "",
    "def style_chart_axes(ax):",
    "    ax.set_facecolor('#FFFFFF')",
    "    ax.grid(True, linestyle='-', linewidth=0.7, alpha=0.85, color='#E2E8F0')",
    "    ax.set_axisbelow(True)",
    "    ax.spines['top'].set_visible(False)",
    "    ax.spines['right'].set_visible(False)",
    "    ax.spines['left'].set_color('#CBD5E1')",
    "    ax.spines['bottom'].set_color('#CBD5E1')",
    "",
    "def set_chart_title(ax, title, *, subtitle=None, xlabel=None, ylabel=None):",
    "    ax.set_title(title, loc='left', pad=14, fontsize=13, fontweight='600', color='#0F172A')",
    "    if subtitle:",
    "        ax.text(0, 1.03, subtitle, transform=ax.transAxes, fontsize=10, color='#64748B', va='bottom')",
    "    if xlabel:",
    "        ax.set_xlabel(xlabel, labelpad=8)",
    "    if ylabel:",
    "        ax.set_ylabel(ylabel, labelpad=8)",
    "",
    "def finalize_legend(ax, *, loc='upper left', ncol=1):",
    "    handles, labels = ax.get_legend_handles_labels()",
    "    if not labels:",
    "        return",
    "    ax.legend(handles, labels, loc=loc, ncol=ncol, frameon=True, framealpha=0.95,",
    "              edgecolor='#E2E8F0', facecolor='#FFFFFF', borderpad=0.6, labelspacing=0.5)",
    "",
    "def new_figure(nrows=1, ncols=1, figsize=None):",
    "    apply_scientific_style()",
    `    if figsize is None:`,
    `        figsize = (${figW}, ${figH})`,
    `    fig, axes = plt.subplots(nrows, ncols, figsize=figsize, layout='constrained')`,
    `    fig.patch.set_facecolor('${SCIENTIFIC_CHART_CONSTANTS.figureFacecolor}')`,
    "    if hasattr(axes, 'flatten'):",
    "        for ax in axes.flatten():",
    "            style_chart_axes(ax)",
    "    else:",
    "        style_chart_axes(axes)",
    "    return fig, axes",
    "",
    "def format_hkt_axis(ax, minticks=4, maxticks=10):",
    "    locator = mdates.AutoDateLocator(tz=HKT, minticks=minticks, maxticks=maxticks)",
    "    formatter = mdates.ConciseDateFormatter(locator, tz=HKT)",
    "    ax.xaxis.set_major_locator(locator)",
    "    ax.xaxis.set_major_formatter(formatter)",
    "    for label in ax.get_xticklabels():",
    "        label.set_rotation(30)",
    "        label.set_horizontalalignment('right')",
    "    ax.set_xlabel('Time (HKT)', labelpad=8)",
    "",
    "def save_chart(fig, filename):",
    "    output_dir = os.environ.get('OUTPUT_DIR', '.')",
    "    os.makedirs(output_dir, exist_ok=True)",
    "    if not filename.endswith('.png'):",
    "        filename = filename + '.png'",
    "    abs_path = os.path.join(output_dir, filename)",
    `    fig.savefig(abs_path, dpi=${dpi}, bbox_inches='tight', facecolor='${SCIENTIFIC_CHART_CONSTANTS.figureFacecolor}', edgecolor='none', pad_inches=0.25)`,
    "    plt.close(fig)",
    "    return os.path.join('outputs', filename)",
    ""
  ].join("\n");
}
