/** Single source of truth for enterprise chart styling and execute_code data/chart helpers. */

export const SCIENTIFIC_CHART_CONSTANTS = {
  figsize: [11, 6.5] as const,
  dpi: 300,
  palette: "deep",
  themeStyle: "whitegrid",
  themeContext: "talk",
  figureFacecolor: "#F8FAFC",
  axesFacecolor: "#FFFFFF",
  gridColor: "#E2E8F0",
  textColor: "#0F172A",
  mutedTextColor: "#64748B",
  spineColor: "#CBD5E1"
} as const;

/** Corporate presentation palette — saturated enough for slides, still distinguishable. */
export const COLOR_CYCLE = [
  "#2563EB",
  "#0D9488",
  "#7C3AED",
  "#D97706",
  "#E11D48",
  "#475569"
] as const;

const DATA_BRIDGE_MINIMAL_EXAMPLE = [
  "combined = build_combined_frame()",
  "fig, ax = new_figure()",
  "set_chart_title(ax, 'Plant overview', ylabel='Value')",
  "for i, col in enumerate(combined.columns): plot_series(ax, combined, col, color_index=i)",
  "format_hkt_axis(ax)",
  "finalize_legend(ax)",
  "path = save_chart(fig, 'overview.png')"
].join("; ");

export function dataBridgeSkillHint(): string {
  return [
    "TOOL DATA BRIDGE (mandatory for execute_code after data tools):",
    "1) load_all_series() returns {label: DataFrame} — iterate `for label, df in load_all_series().items()`; NEVER `for entry in load_all_series()` (entry is a string key, not a manifest dict).",
    "2) Prefer build_combined_frame() for a wide HKT-indexed table; use manifest label or col_series(combined, label) — never guess column names like combined['short_name'].",
    "3) Helpers: load_series_by_label, items_to_frame, normalize_status, resample_status_15m, series_short_label.",
    "4) Do NOT open outputs/.tool_cache/*_manifest.json by hand.",
    "5) pandas 3: .ffill()/.bfill(); never fillna(method=...); pd.concat(..., sort=False).",
    "6) One execute_code pass ending in save_chart — no debug-only scripts (print columns/shape only).",
    "7) Before plotting: data_coverage(combined) — skip or note columns with 0 valid points; wide table rows are sparse (outer join).",
    `Minimal pattern: ${DATA_BRIDGE_MINIMAL_EXAMPLE}`
  ].join(" ");
}

export function scientificChartSkillHint(): string {
  const [w, h] = SCIENTIFIC_CHART_CONSTANTS.figsize;
  return [
    "ENTERPRISE CHARTS (mandatory for any figure — fixed presentation style for corporate reports):",
    `Use new_figure(), set_chart_title(ax, title, ylabel=...), plot_series(), chart_color(i), format_hkt_axis(ax), finalize_legend(ax), save_chart(fig, filename) — dpi=${SCIENTIFIC_CHART_CONSTANTS.dpi}, figsize=(${w}, ${h}).`,
    "Style is auto-applied (whitegrid, corporate palette, left-aligned title, clean spines) — do NOT customize colors/fonts manually.",
    "DEFAULT timeseries = line chart: plot_series(ax, combined, col) drops NaN and breaks lines at gaps — do NOT interpolate/fill_between across missing spans by default.",
    "Use plot_status_step(ax, combined, col) only for discrete status (Run_Status/S); never fill_between on power/temperature/flow.",
    "NEVER hard-code COLOR_CYCLE[6] — use chart_color(i) or COLOR_CYCLE[i % len(COLOR_CYCLE)].",
    "mdates is pre-imported — use format_hkt_axis(ax); never mdates.DateFormatter(..., tz=...).",
    "Do NOT sns.set_style/set_theme with custom palettes; do NOT plt.savefig directly.",
    "English-only on-chart text; every chart needs set_chart_title() with a clear business title; every chart script must call save_chart()."
  ].join(" ");
}

/** Detect chart intent without save_chart output — for execute_code sanity check. */
export function chartSanityViolation(userCode: string, newPngCount: number): string | null {
  const trimmed = userCode.trim();
  if (!trimmed) {
    return null;
  }
  const chartIntent =
    /\bnew_figure\s*\(|\bplot_series\s*\(|\bplt\.subplots\s*\(|\bplt\.plot\s*\(|\b\.plot\s*\(|\baxes\[\d+\]\.plot\s*\(/i.test(trimmed);
  if (/\bsave_chart\s*\(/i.test(trimmed) || newPngCount > 0) {
    return null;
  }
  const debugOnly =
    /\bprint\s*\(/i.test(trimmed)
    && /\b(build_combined_frame|load_all_series|\.columns|\.shape|data_coverage)\b/i.test(trimmed);
  if (debugOnly && !chartIntent) {
    return "Debug-only execute_code (print columns/shape/coverage) is not allowed after data tools. One pass ending in save_chart().";
  }
  if (chartIntent) {
    return "Chart code detected but save_chart() was not called and no PNG was generated. End chart scripts with save_chart(fig, 'name.png').";
  }
  return null;
}

export function executeCodeInjectedHeader(): string {
  const [figW, figH] = SCIENTIFIC_CHART_CONSTANTS.figsize;
  const dpi = SCIENTIFIC_CHART_CONSTANTS.dpi;
  const colors = COLOR_CYCLE.map((c) => `"${c}"`).join(", ");

  return [
    "# Auto-injected by BuildingAgent execute_code",
    "import json, os, re",
    "from zoneinfo import ZoneInfo",
    "import pandas as pd",
    "import numpy as np",
    "import matplotlib",
    "matplotlib.use('Agg')",
    "import matplotlib.pyplot as plt",
    "import matplotlib.dates as mdates",
    "import seaborn as sns",
    'HKT = ZoneInfo("Asia/Hong_Kong")',
    "",
    "def load_tool_manifest():",
    "    # entries: [{label, data_file, tool, toolCallId}] — use entry['label'], not entry['name']",
    "    path = os.environ.get('TOOL_CACHE_MANIFEST', '')",
    "    if path and os.path.isfile(path):",
    "        with open(path, encoding='utf-8') as f:",
    "            return json.load(f)",
    "    return {'requestId': os.environ.get('REQUEST_ID', ''), 'entries': []}",
    "",
    "def load_cached_items(data_file):",
    "    with open(data_file, encoding='utf-8') as f:",
    "        payload = json.load(f)",
    "    return payload.get('items', payload) if isinstance(payload, dict) else payload",
    "",
    "def items_to_frame(items, value_col='value_num'):",
    "    df = pd.DataFrame(items)",
    "    if df.empty:",
    "        return df",
    "    if 'ts' in df.columns:",
    "        df['ts'] = pd.to_datetime(df['ts'], utc=True).dt.tz_convert(HKT)",
    "        df = df.set_index('ts').sort_index()",
    "    if value_col in df.columns:",
    "        df[value_col] = pd.to_numeric(df[value_col], errors='coerce')",
    "    return df",
    "",
    "def load_series_by_label(label):",
    "    manifest = load_tool_manifest()",
    "    for entry in manifest.get('entries', []):",
    "        if entry.get('label') == label:",
    "            return items_to_frame(load_cached_items(entry['data_file']))",
    "    raise KeyError(f'No manifest entry for label={label!r}')",
    "",
    "def load_all_series():",
    "    # Returns dict[str, DataFrame] keyed by manifest label — NOT a list of entries.",
    "    out = {}",
    "    for entry in load_tool_manifest().get('entries', []):",
    "        label = entry.get('label')",
    "        if not label:",
    "            continue",
    "        out[label] = items_to_frame(load_cached_items(entry['data_file']))",
    "    return out",
    "",
    "def series_short_label(label):",
    "    # Generic: last token after '-' or '_' (e.g. Plant-A-Temp01 -> Temp01). No domain alias map.",
    "    if not label:",
    "        return label",
    "    return re.split(r'[-_]', str(label))[-1]",
    "",
    "def build_combined_frame(series_dict=None, value_col='value_num'):",
    "    if series_dict is None:",
    "        series_dict = load_all_series()",
    "    parts = []",
    "    used_names = set()",
    "    for label, df in series_dict.items():",
    "        if df is None or df.empty or value_col not in df.columns:",
    "            continue",
    "        short = series_short_label(label)",
    "        col_name = short if short not in used_names else label",
    "        used_names.add(col_name)",
    "        col = df[value_col].rename(col_name)",
    "        parts.append(col)",
    "    if not parts:",
    "        return pd.DataFrame()",
    "    return pd.concat(parts, axis=1, sort=False).sort_index()",
    "",
    "def col_series(combined, *names):",
    "    # Match full manifest label or short suffix; return empty Series if not found (no KeyError).",
    "    empty = pd.Series(dtype=float)",
    "    if combined is None or getattr(combined, 'empty', True):",
    "        return empty",
    "    for name in names:",
    "        if name in combined.columns:",
    "            return combined[name]",
    "        short = series_short_label(name)",
    "        if short in combined.columns:",
    "            return combined[short]",
    "        for col in combined.columns:",
    "            if col == name or series_short_label(col) == short:",
    "                return combined[col]",
    "    return empty",
    "",
    "def normalize_status(series):",
    "    s = pd.to_numeric(series, errors='coerce')",
    "    if s.notna().any():",
    "        return (s.fillna(0) > 0).astype(int)",
    "    text = series.astype(str).str.strip().str.upper()",
    "    on_tokens = {'ON', 'TRUE', 'YES', 'RUN', 'RUNNING', '1'}",
    "    return text.isin(on_tokens).astype(int)",
    "",
    "def resample_status_15m(df, value_col='value_num'):",
    "    if df is None or df.empty or value_col not in df.columns:",
    "        return pd.Series(dtype=int)",
    "    status = normalize_status(df[value_col])",
    "    return status.resample('15min').max().ffill().fillna(0).astype(int)",
    "",
    `COLOR_CYCLE = [${colors}]`,
    "",
    "def chart_color(i):",
    "    return COLOR_CYCLE[int(i) % len(COLOR_CYCLE)]",
    "",
    "def data_coverage(frame):",
    "    if frame is None or getattr(frame, 'empty', True):",
    "        return pd.Series(dtype=int)",
    "    return frame.notna().sum()",
    "",
    "def plot_series(ax, data, col=None, *, color=None, label=None, color_index=0, linewidth=2.0, marker_if_le=12, **kwargs):",
    "    # Default timeseries: line chart, dropna (gaps break the line). Returns None if no valid points.",
    "    if isinstance(data, pd.Series):",
    "        series = data.dropna()",
    "        use_label = label or (str(data.name) if data.name else 'series')",
    "    elif isinstance(data, pd.DataFrame):",
    "        if col is None or col not in data.columns:",
    "            return None",
    "        series = data[col].dropna()",
    "        use_label = label or str(col)",
    "    else:",
    "        return None",
    "    if series.empty:",
    "        return None",
    "    use_color = color if color is not None else chart_color(color_index)",
    "    plot_kw = {'label': use_label, 'color': use_color, 'linewidth': linewidth}",
    "    if len(series) <= marker_if_le:",
    "        plot_kw['marker'] = 'o'",
    "        plot_kw['markersize'] = 3",
    "    return ax.plot(series.index, series.values, **plot_kw, **kwargs)[0]",
    "",
    "def plot_status_step(ax, data, col=None, *, color='orange', alpha=0.25, label=None, **kwargs):",
    "    # Discrete status only (Run_Status, S, etc.) — step fill, not for analog signals.",
    "    if isinstance(data, pd.DataFrame):",
    "        if col is None or col not in data.columns:",
    "            return None",
    "        series = normalize_status(data[col]).dropna()",
    "        use_label = label or str(col)",
    "    elif isinstance(data, pd.Series):",
    "        series = normalize_status(data).dropna()",
    "        use_label = label or (str(data.name) if data.name else 'status')",
    "    else:",
    "        return None",
    "    if series.empty:",
    "        return None",
    "    return ax.fill_between(series.index, 0, series.values, step='post', alpha=alpha, color=color, label=use_label, **kwargs)",
    "",
    "def apply_scientific_style():",
    `    sns.set_theme(style="${SCIENTIFIC_CHART_CONSTANTS.themeStyle}", context="${SCIENTIFIC_CHART_CONSTANTS.themeContext}", palette="${SCIENTIFIC_CHART_CONSTANTS.palette}")`,
    "    plt.rcParams.update({",
    `        'figure.facecolor': '${SCIENTIFIC_CHART_CONSTANTS.figureFacecolor}',`,
    `        'axes.facecolor': '${SCIENTIFIC_CHART_CONSTANTS.axesFacecolor}',`,
    `        'axes.edgecolor': '${SCIENTIFIC_CHART_CONSTANTS.spineColor}',`,
    `        'axes.labelcolor': '${SCIENTIFIC_CHART_CONSTANTS.mutedTextColor}',`,
    `        'text.color': '${SCIENTIFIC_CHART_CONSTANTS.textColor}',`,
    `        'xtick.color': '${SCIENTIFIC_CHART_CONSTANTS.mutedTextColor}',`,
    `        'ytick.color': '${SCIENTIFIC_CHART_CONSTANTS.mutedTextColor}',`,
    "        'axes.linewidth': 0.9,",
    "        'axes.titleweight': '600',",
    "        'axes.titlesize': 13,",
    "        'axes.labelsize': 11,",
    "        'font.size': 11,",
    "        'legend.fontsize': 10,",
    "        'xtick.labelsize': 10,",
    "        'ytick.labelsize': 10,",
    "        'grid.color': '#E2E8F0',",
    "        'grid.linewidth': 0.7,",
    "        'grid.alpha': 0.9,",
    "        'lines.linewidth': 2.0,",
    "        'font.family': 'sans-serif',",
    "    })",
    "",
    "def style_chart_axes(ax):",
    "    ax.set_facecolor('#FFFFFF')",
    "    ax.grid(True, linestyle='-', linewidth=0.7, alpha=0.85, color='#E2E8F0')",
    "    ax.set_axisbelow(True)",
    "    ax.spines['top'].set_visible(False)",
    "    ax.spines['right'].set_visible(False)",
    "    ax.spines['left'].set_color('#CBD5E1')",
    "    ax.spines['bottom'].set_color('#CBD5E1')",
    "",
    "def set_chart_title(ax, title, *, subtitle=None, xlabel=None, ylabel=None):",
    "    ax.set_title(title, loc='left', pad=14, fontsize=13, fontweight='600', color='#0F172A')",
    "    if subtitle:",
    "        ax.text(0, 1.03, subtitle, transform=ax.transAxes, fontsize=10, color='#64748B', va='bottom')",
    "    if xlabel:",
    "        ax.set_xlabel(xlabel, labelpad=8)",
    "    if ylabel:",
    "        ax.set_ylabel(ylabel, labelpad=8)",
    "",
    "def finalize_legend(ax, *, loc='upper left', ncol=1):",
    "    handles, labels = ax.get_legend_handles_labels()",
    "    if not labels:",
    "        return",
    "    ax.legend(handles, labels, loc=loc, ncol=ncol, frameon=True, framealpha=0.95,",
    "              edgecolor='#E2E8F0', facecolor='#FFFFFF', borderpad=0.6, labelspacing=0.5)",
    "",
    "def new_figure(nrows=1, ncols=1, figsize=None):",
    "    apply_scientific_style()",
    `    if figsize is None:`,
    `        figsize = (${figW}, ${figH})`,
    `    fig, axes = plt.subplots(nrows, ncols, figsize=figsize, layout='constrained')`,
    `    fig.patch.set_facecolor('${SCIENTIFIC_CHART_CONSTANTS.figureFacecolor}')`,
    "    if hasattr(axes, 'flatten'):",
    "        for ax in axes.flatten():",
    "            style_chart_axes(ax)",
    "    else:",
    "        style_chart_axes(axes)",
    "    return fig, axes",
    "",
    "def format_hkt_axis(ax, hour_interval=3):",
    "    ax.xaxis.set_major_formatter(mdates.DateFormatter('%H:%M'))",
    "    ax.xaxis.set_major_locator(mdates.HourLocator(interval=hour_interval))",
    "    for label in ax.get_xticklabels():",
    "        label.set_rotation(30)",
    "        label.set_horizontalalignment('right')",
    "    ax.set_xlabel('Time (HKT)', labelpad=8)",
    "",
    "def save_chart(fig, filename):",
    "    output_dir = os.environ.get('OUTPUT_DIR', '.')",
    "    os.makedirs(output_dir, exist_ok=True)",
    "    if not filename.endswith('.png'):",
    "        filename = filename + '.png'",
    "    abs_path = os.path.join(output_dir, filename)",
    `    fig.savefig(abs_path, dpi=${dpi}, bbox_inches='tight', facecolor='${SCIENTIFIC_CHART_CONSTANTS.figureFacecolor}', edgecolor='none', pad_inches=0.25)`,
    "    plt.close(fig)",
    "    return os.path.join('outputs', filename)",
    ""
  ].join("\n");
}
